@startuml

class Emoji {
    name
}

class EmojiCount {
    type
    count
}

class Channel {
    id
}

class User {
    id
    name
}

class MessageCount {
   count
}

Channel "1" -- "*" EmojiCount
EmojiCount "*" -- "1" Emoji
Channel "1" -- "*" MessageCount
MessageCount "*" -- "1" User

@enduml